# Generated by Django 3.1.3 on 2020-11-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Client',
        ),
    ]
