# Generated by Django 3.1.2 on 2020-11-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20201117_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientTodo',
        ),
    ]
