# Generated by Django 3.1.2 on 2020-11-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_delete_clienttodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-date_created']},
        ),
    ]
