# Generated by Django 3.1.2 on 2020-11-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20201121_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='make_up',
            field=models.DateField(null=True),
        ),
    ]
