# Generated by Django 3.1.2 on 2020-11-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_todo_make_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_completed',
            field=models.BooleanField(default=False),
        ),
    ]
